###oauth-server:【oauth_client_details表中authorized_grant_types字段定义客户端使用的许可类型】 资源拥有者凭证许可类型，获取access_token,refresh_token
#&username=writer&password=writer
POST {{url}}/oauth/token?grant_type=password&client_id=userservice1&client_secret=1234&username=writer&password=writer
Accept: application/json
Cache-Control: no-cache




###oauth-server: access_token校验合法性
GET {{url}}/oauth/check_token?client_id=userservice1&client_secret=1234&token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgtdXNlciJdLCJzY29wZSI6WyJGT08iXSwiZXhwIjoxNjA0NDAyMDEzLCJhdXRob3JpdGllcyI6WyJSRUFEIiwiV1JJVEUiXSwianRpIjoiYzFlNTYwMzYtNGI3NC00NGVlLThlYjQtM2ZmMmM4MDE3YjFiIiwiY2xpZW50X2lkIjoidXNlcnNlcnZpY2UyIn0.AkT8Ew5-TuDYZ5Psks6V__nBHDCVqL4PPG4viGCUARcF9THbl_ZIQLM7v6GbewLkO7JdA20x1HFd8L6o5l6IOIUpRoVEmsMbCi6m1UVGKlhd196kVLjLaf2w2LlMKBn-plZ-6GXq_JskcGdMPXSym-2-DsM0Fqe6r1jAxYBWxMqYlKimENq-LrAPCiClPztcoQQRpss3zEnmkSa-YjQNgYiY_p8Kt6nZfTnJfVvne0AlvJUf5RVunhyWhnASuVYFph1uyxs206SofZK0VdhSkLIuAP9BrorX5l5ISwKKZzwsG2lv7VIUTjGlfzSxB9yA2wOwtgOhhkpE9URnyOEoUA
Accept: application/json
Cache-Control: no-cache



###oauth-server:客户端授权许可类型，获取access_token
POST {{url}}/oauth/token?grant_type=client_credentials&client_id=userservice2&client_secret=1234
Accept: application/json
Cache-Control: no-cache
#Authorization: Basic dXNlcnNlcnZpY2UyOjEyMzQ=

###
POST {{url}}/login?username=reader&password=reader
Accept: */*
Cache-Control: no-cache


### 获取授权码,需要浏览器访问，库中设置autoapprove：false 非自动授权，账号登录后需要手动点击授权
GET  http://localhost:9090/oauth/authorize?response_type=code&client_id=userservice3&redirect_uri=http://localhost:9091/user/common/read

###通过授权码获取访问令牌
POST {{url}}/oauth/token?grant_type=authorization_code&client_id=userservice3&client_secret=1234&code=QjdgzM&redirect_uri=http://localhost:9091/user/common/read
Accept: application/json
Cache-Control: no-cache


### 不需要校验
GET {{url}}/hello/
Accept: application/json
Cache-Control: no-cache

### 需传入access_token 才能进行访问
POST {{url}}/user/common/write
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgtdXNlciJdLCJ1c2VyX25hbWUiOiJ3cml0ZXIiLCJ1c2VyRGV0YWlsIjp7InBhc3N3b3JkIjpudWxsLCJ1c2VybmFtZSI6IndyaXRlciIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJSRUFELFdSSVRFIn1dLCJhY2NvdW50Tm9uRXhwaXJlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZSwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjp0cnVlLCJlbmFibGVkIjp0cnVlfSwic2NvcGUiOlsiRk9PIl0sImV4cCI6MTYwNjgxNDk2MCwiYXV0aG9yaXRpZXMiOlsiUkVBRCxXUklURSJdLCJqdGkiOiJlM2E5YmIzNC02Y2Y1LTQ4YzEtYmM2ZS1iY2MzOTFkNjQxYjYiLCJjbGllbnRfaWQiOiJ1c2Vyc2VydmljZTMifQ.VxO30e_vPLRhPXMtiinth4Qs5kv4QXZG3PIRv4Qpucjy46oGdscgEPpKvjEKiIyqYqhxV4Hh61VEsJ3u5mb1gUJe7cRrInQ2MEeLm6lQD1ZkIkE6eSodmdru9C_pz1UoM4xAoP7pDY1GitL9KFlgrP1XtK6f8iQyrLADhx99D7hRveCi5Y6Fh_SDmGdKMyzLGTj8EknBGCip4jV9YRzTjcqJvqqaayKA8djNO12ccz7h1ix-NJ6iWdRg7S-3cO71w6vebMKg6VTn-43y7cODnC6jn45eyBMhTPPBsDppRUR51_gJXVUxafb0Lc1e2jUz4gho1dnLbphBJhndlF0iyw


###server 端获取登录验证码
GET {{url}}/demo/produceCode
Accept: */*
Cache-Control: no-cache

### 自定义json登录并加验证码
POST {{url}}/doLogin?code=3614
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8

{
  "uname": "admin",
  "pwd": "admin"
}

###
GET {{url}}/logout
Accept: */*
Cache-Control: no-cache

### client 访问资源服务器接口
GET {{url}}/remoteApi/read
Accept: *
Cache-Control: no-cache

