###oauth-server:【oauth_client_details表中authorized_grant_types字段定义客户端使用的许可类型】 资源拥有者凭证许可类型，获取access_token,refresh_token
#&username=writer&password=writer
POST {{url}}/oauth/token?grant_type=password&client_id=userservice1&client_secret=1234&username=writer&password=writer
Accept: application/json
Cache-Control: no-cache




###oauth-server: access_token校验合法性
GET {{url}}/oauth/check_token?client_id=userservice1&client_secret=1234&token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgtdXNlciJdLCJzY29wZSI6WyJGT08iXSwiZXhwIjoxNjA0NDAyMDEzLCJhdXRob3JpdGllcyI6WyJSRUFEIiwiV1JJVEUiXSwianRpIjoiYzFlNTYwMzYtNGI3NC00NGVlLThlYjQtM2ZmMmM4MDE3YjFiIiwiY2xpZW50X2lkIjoidXNlcnNlcnZpY2UyIn0.AkT8Ew5-TuDYZ5Psks6V__nBHDCVqL4PPG4viGCUARcF9THbl_ZIQLM7v6GbewLkO7JdA20x1HFd8L6o5l6IOIUpRoVEmsMbCi6m1UVGKlhd196kVLjLaf2w2LlMKBn-plZ-6GXq_JskcGdMPXSym-2-DsM0Fqe6r1jAxYBWxMqYlKimENq-LrAPCiClPztcoQQRpss3zEnmkSa-YjQNgYiY_p8Kt6nZfTnJfVvne0AlvJUf5RVunhyWhnASuVYFph1uyxs206SofZK0VdhSkLIuAP9BrorX5l5ISwKKZzwsG2lv7VIUTjGlfzSxB9yA2wOwtgOhhkpE9URnyOEoUA
Accept: application/json
Cache-Control: no-cache



###oauth-server:客户端授权许可类型，获取access_token
POST {{url}}/oauth/token?grant_type=client_credentials&client_id=userservice2&client_secret=1234
Accept: application/json
Cache-Control: no-cache
#Authorization: Basic dXNlcnNlcnZpY2UyOjEyMzQ=



### 获取授权码,需要浏览器访问，库中设置autoapprove：false 非自动授权，账号登录后需要手动点击授权
 http://localhost:9090/oauth/authorize?response_type=code&client_id=userservice3&redirect_uri=https://baidu.com



###通过授权码获取访问令牌
POST {{url}}/oauth/token?grant_type=authorization_code&client_id=userservice3&client_secret=1234&code=U6lUEZ&redirect_uri=https://baidu.com
Accept: application/json
Cache-Control: no-cache


###
GET {{url}}/hello/
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgtdXNlciJdLCJ1c2VyX25hbWUiOiJyZWFkZXIiLCJ1c2VyRGV0YWlsIjp7InBhc3N3b3JkIjpudWxsLCJ1c2VybmFtZSI6InJlYWRlciIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJSRUFEIn1dLCJhY2NvdW50Tm9uRXhwaXJlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZSwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjp0cnVlLCJlbmFibGVkIjp0cnVlfSwic2NvcGUiOlsiRk9PIl0sImV4cCI6MTYwNDY2MDQyNywiYXV0aG9yaXRpZXMiOlsiUkVBRCJdLCJqdGkiOiIyZDc2OTM2MC1kZWUwLTRhMjctYjk3OS0xMjc1NTI5NDY0NzIiLCJjbGllbnRfaWQiOiJ1c2Vyc2VydmljZTMifQ.A4LJGhAgjhn2nNK2GCZWXNj0FpZNqDcFdJ3NIuUI-qwi9aw-yO8dEOEjnwRmIteIQCrika_PUEx4Qcq892fM_spG9rAM5apIRmlBsAMYdqKp0VFnvP3OgnkFdyIlSEJ_IeH3eUN3NikeIc78hAPLKSWXL1jelSoMntOSuyMR9oP6LdUv4_tDGTywisDnqy24uM2NIbs1gsliLjGTLN5vapG7LQWFFDVgA1RT0Z-ralx_B8Y0xNKookInNVD9ozxUqyP2qDytAth96UIYU4MA9II-QOkH7akwk5MH6A9gKa8w8rw24cbVphOgEqWCUGL8OWjrtpvbTjscwoDMd_eewg


###
GET {{url}}/user/read
Accept: *
Cache-Control: no-cache
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgtdXNlciJdLCJzY29wZSI6WyJGT08iXSwiZXhwIjoxNjA0NDAyMDEzLCJhdXRob3JpdGllcyI6WyJSRUFEIiwiV1JJVEUiXSwianRpIjoiYzFlNTYwMzYtNGI3NC00NGVlLThlYjQtM2ZmMmM4MDE3YjFiIiwiY2xpZW50X2lkIjoidXNlcnNlcnZpY2UyIn0.AkT8Ew5-TuDYZ5Psks6V__nBHDCVqL4PPG4viGCUARcF9THbl_ZIQLM7v6GbewLkO7JdA20x1HFd8L6o5l6IOIUpRoVEmsMbCi6m1UVGKlhd196kVLjLaf2w2LlMKBn-plZ-6GXq_JskcGdMPXSym-2-DsM0Fqe6r1jAxYBWxMqYlKimENq-LrAPCiClPztcoQQRpss3zEnmkSa-YjQNgYiY_p8Kt6nZfTnJfVvne0AlvJUf5RVunhyWhnASuVYFph1uyxs206SofZK0VdhSkLIuAP9BrorX5l5ISwKKZzwsG2lv7VIUTjGlfzSxB9yA2wOwtgOhhkpE9URnyOEoUA

###
POST {{url}}/user/write
Accept: application/json
Cache-Control: no-cache
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgtdXNlciJdLCJ1c2VyX25hbWUiOiJyZWFkZXIiLCJ1c2VyRGV0YWlsIjp7InBhc3N3b3JkIjpudWxsLCJ1c2VybmFtZSI6InJlYWRlciIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJSRUFEIn1dLCJhY2NvdW50Tm9uRXhwaXJlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZSwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjp0cnVlLCJlbmFibGVkIjp0cnVlfSwic2NvcGUiOlsiRk9PIl0sImV4cCI6MTYwNDY2MDQyNywiYXV0aG9yaXRpZXMiOlsiUkVBRCJdLCJqdGkiOiIyZDc2OTM2MC1kZWUwLTRhMjctYjk3OS0xMjc1NTI5NDY0NzIiLCJjbGllbnRfaWQiOiJ1c2Vyc2VydmljZTMifQ.A4LJGhAgjhn2nNK2GCZWXNj0FpZNqDcFdJ3NIuUI-qwi9aw-yO8dEOEjnwRmIteIQCrika_PUEx4Qcq892fM_spG9rAM5apIRmlBsAMYdqKp0VFnvP3OgnkFdyIlSEJ_IeH3eUN3NikeIc78hAPLKSWXL1jelSoMntOSuyMR9oP6LdUv4_tDGTywisDnqy24uM2NIbs1gsliLjGTLN5vapG7LQWFFDVgA1RT0Z-ralx_B8Y0xNKookInNVD9ozxUqyP2qDytAth96UIYU4MA9II-QOkH7akwk5MH6A9gKa8w8rw24cbVphOgEqWCUGL8OWjrtpvbTjscwoDMd_eewg


###
GET {{url}}/remoteApi
Accept: application/json
Cache-Control: no-cache