server:
  port: 9093
spring:
  application.name: review-1
  profiles.active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

---
spring.profiles: dev

# 指定log4j2作为日志记录
logging:
  config: classpath:log4j2-9093.xml
