###
GET {{url}}/user/get
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/user/admin
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/user/user
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/user/remember
Accept: */*
Cache-Control: no-cache

###登录
POST {{url}}/doLogin?uname=user&pwd=user&remember-me=on
Accept: */*
Cache-Control: no-cache

###
POST {{url}}/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/json